"""add language to posts

Revision ID: 108aae22e1cd
Revises: 3123d8294d03
Create Date: 2022-03-04 20:14:38.256919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108aae22e1cd'
down_revision = '3123d8294d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
