"""user table

Revision ID: 801784c3776b
Revises: 9484e470db83
Create Date: 2022-02-28 00:02:54.575979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801784c3776b'
down_revision = '9484e470db83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
