"""user table

Revision ID: 9484e470db83
Revises: 35c94acd4b9f
Create Date: 2022-02-27 21:34:14.842044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9484e470db83'
down_revision = '35c94acd4b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_modify', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_modify')
    # ### end Alembic commands ###
